#  echo -n "krm(#)666" | base64  -- 加密
#  echo -n "a3JtKCMpNjY2" | base64 -d -- 解密
#  echo -n "dev" | base64  -- 加密
apiVersion: v1
kind: Secret
metadata:
  name: mongo
data:
  MONGO_INITDB_ROOT_USERNAME: ZGV2
  MONGO_INITDB_ROOT_PASSWORD: a3JtKCMpNjY2
