// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usercenter

import (
	"github.com/costa92/krm/internal/pkg/bootstrap"
	"github.com/costa92/krm/internal/usercenter/biz"
	"github.com/costa92/krm/internal/usercenter/server"
	"github.com/costa92/krm/internal/usercenter/service"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

func wireApp(appInfo bootstrap.AppInfo, config *server.Config) (*kratos.App, func(), error) {
	logger := bootstrap.NewLogger(appInfo)
	appConfig := bootstrap.AppConfig{
		Info:   appInfo,
		Logger: logger,
	}
	bizBiz := biz.NewBiz()
	userCenterService := service.NewUserCenterService(bizBiz)
	v := server.NewMiddlewares(logger)
	httpServer := server.NewHTTPServer(config, userCenterService, v)
	grpcServer := server.NewGRPCServer(config, userCenterService, v)
	v2 := server.NewServers(httpServer, grpcServer)
	app := bootstrap.NewApp(appConfig, v2...)
	return app, func() {
	}, nil
}
